POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo evento 2",
  "details":  null,
  "maximumAttendees": 1
}

### 
POST http://localhost:3333/events/5280eb07-53fa-45dc-ac09-f429577e3aed/attendees
Content-Type: application/json

{
  "name": "Pedro Germano",
  "email": "pedrogermano@gmail.com"
}